### ISSUE TITLE
Outdated Farming mod

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#1]
Ton mod "Farming" ('mods/farming') est l'une des toutes premières versions de "Farming Plus" par PilzAdam, où il faut labourer des blocs de terre pour espérer obtenir des graines de blé, coton ou citrouille. C'est incroyablement ancien (2012), avec des appels à minetest.env() et des hoes en bois pas générique par exemple. 

-- Le_Docteur

**Comment by paly2** [comment]
Pardon, je n'avais pas committé la version de farming_plus qui se trouve en réalité actuellement sur le serveur. C'est fait maintenant.

**Comment by mgl512** [comment]
"Farming Plus" reste un vieux mod abandonné sans être fini: il manque une ligne "on_use" pour la rhubarbe (je l'ai beaucoup utilisé en local). La citrouille qui ne donne qu'une graine est ce qu'il y a de plus ennuyeux dans ce mod mais ça se corrige aussi. En dehors de ça, je pense qu'il est ok.

Le diff de 'farming_plus/rhubarb.lua':
```
--- a/farming_plus/rhubarb.lua
+++ b/farming_plus/rhubarb.lua
@@ -65,6 +65,7 @@ minetest.register_node("farming_plus:rhubarb", {
 minetest.register_craftitem("farming_plus:rhubarb_item", {
        description = S("Rhubarb"),
        inventory_image = "farming_rhubarb.png",
+       on_use = minetest.item_eat(2),
 })

```
Sinon ça ne fait rien quand on essaie de la manger. Le mod "Hunger" la prend en compte après ça.

**Comment by paly2** [comment]
Penses-tu qu'il vaille mieux remplacer farming_plus par [DocFarming](https://forum.minetest.net/viewtopic.php?id=3948) ou [JKFarming](https://forum.minetest.net/viewtopic.php?id=7038) ? En attendant je rajoute cette ligne

**Comment by mgl512** [comment]
> Penses-tu qu'il vaille mieux remplacer farming_plus par DocFarming ou JKFarming ? 

Farming Plus est très bien comparé à ces deux là. 

L'ancienne version de "Farming Plus" que tu avais installée a céé des craftitems farming:cotton_seed et farming:wheat_seed qui sont connus sous les noms farming:seed_cotton et farming:seed_wheat dans le mod "Farming (default)" actuel et pas repris dans la version la plus récente de "Farming Plus". Si des joueurs en avaient sous les anciens noms, ça devient des "unknown nodes". Il faudra soit leur dire, soit créer des alias à la fin du fichier 'init.lua' de "Farmng Plus" pour redonner leur nom d'aujourd'hui à ces objets de l'ancienne version.  

Des joueurs en avaient s'ils ont deviné qu'il fallait labourer de la terre à la hoe pour en obtenir ou si tu en as donné.

**Comment by paly2** [comment]
Ok, merci, donc je laisse farming_plus
