### ISSUE TITLE
Grief made in spain

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#10]
On a ce joueur espagnol qui a les comptes elprincipiante, elcrak et ELMEJOR21 sous une IP et maintenant au moins deux (BOB123, ELLEGENDARIO) sous une autre (200.117....). A vérifier qu'il n'est pas (de mémoire) AUGUSTINXD et UGA99 aussi, deux joueurs qui ont posé des rectangles immenses d'aspen ou de pierre rouge ça et là sans plus rien faire après. 

Il fait des maisons/griefs de plus en plus énormes partout. Là c'est un rectangle de grief de 50x100 sur un lac à l'est du spawn. 

Et ses pseudos: le débutant, le crack, le meilleur, le légendaire...

**Comment by paly2** [comment]
Effectivement, AGUSTINXD, AGU999, JORDAN, PEDRORIOS, BOB123, ELLEGENDARIO, elprincipiante, elcrak, ELMEJOR21, ainsi qu'un certain palinge (avec un N) ne font qu'un. Ces quelques comptes cumulent énormément d'areas.

Pour éviter cela, je suis très intéressé par le mod [names_per_ip](https://github.com/SmallJoker/names_per_ip), qui l'imite le nombre de comptes par IP, et qui, en plus, permettrait de faire une commande /ip plus performante (qui fonctionnerait même quand le joueur n'est pas connecté), vu que le mod enregistre toutes les IPs.

**Comment by mgl512** [comment]
Mais c'est un psychopathe ce joueur, un schizophrène du cube !

En plus il change d'IP ou sa box crashe.

Le mod a l'air bien. Je vais me faire un peu maltraiter avec tous les comptes que j'ai usurpés + public + Usurpateur666.

**Comment by paly2** [comment]
C'est bon, le mod names_per_ip a été ajouté https://github.com/paly2/Mynetest-server/commit/f4bc82670546cdd697fdb8036b175ff18965b1ae , la commande ip améliorée https://github.com/paly2/Mynetest-server/commit/d99b7d6c7936f0c3265ed09c6a44fbb8e25e0b7a. Elcrak&co ne pourra plus connecter que deux comptes depuis la même IP.

**Comment by mgl512** [comment]
Il change tout le temps d'IP. J'en ai noté 3.

**Comment by paly2** [comment]
Il change d'IP, mais change-t-il de compte ? J'avais (avec l'aide d'AkitoNaaki93) essayé de lui expliquer qu'un compte suffisait. Le problème était bien qu'il ne savait pas comment obtenir des ressources, visiblement, il a maintenant compris qu'il fallait miner.

Bizarre que la commande /ipnames whois ne rapporte pas paul parmi eux, parce qu'elle fonctionne comme la fonction que le mod register avec minetest.register_on_prejoinplayer. Il faudra que je regarde ça de plus près.
Ce mod fournit une et une seule commande, la commande /ipnames, qui propose elle-même un certain nombre de "sous-commandes". C'est vrai qu'il manque un certain nombre de commandes (à commencer par la commande /ip qui aurait pu directement s'y trouver).

**Comment by mgl512** [comment]
Il ne change pas de compte mais je ne peux pas m'empêcher de penser qu'il change d'IP parce qu'il *voudrait* créer d'autres comptes mais que le mod l'en empêche, comme pour le frère d'Uraza. Son IP était stable avant le mod, je surveille ce joueur depuis plus d'une semaine maintenant. 


> Le problème était bien qu'il ne savait pas comment obtenir des ressources

- J'ai un peu de mal à croire qu'un joueur qui sait utiliser le usebug de latence des blocs protégés pour aller vider les coffres de jg sous différents pseudos ne connaisse rien au jeu. Sous le premier pseudo où il s'est fait remarquer, elprincipiante ("le débutant"), il savait comment faire des cultures, une source d'eau infinie, faire pousser du papyrus. Il a abandonné ce compte à jamais pour se connecter sous le pseudo de elcrak ("le crack"). Il m'a dit qu'il ne connaissait pas du tout elprincipiante (il m'a refait le coup à chaque nouveau pseudo) mais il est venu directement à son ancienne maison-grief pour en commencer une autre identique juste à côté. C'était évident jusqu'aux pseudos que c'était le même joueur.
 
- Il ne fait pas que transférer ses ressources entre ses comptes mais il utilise chaque compte pour faire des maison-griefs. BOB123 a construit, à l'est de chez annie, une plateforme aérienne en pierre où il a planté des arbres. AGUSTINXD a rasé une forêt. Il l'a utilisée pour poser un tapis de bois d'aspen de grande taille en haut d'une falaise et il a disparu. Rollbacké. AGU999 a creusé des tranchées et posé un tapis de pierre rouge xdecor de taille similaire là ou Youfie s'est installé, au nord du truc plein d'eau, worldedité. 


> Ce mod fournit une et une seule commande, la commande /ipnames

Je connais tout le mod alors, les 3 sous-commandes whois, (un)ignore, list.

**Comment by paly2** [comment]
Il change d'IP mais non, il n'essaie pas de se servir des nouvelles IP pour connecter d'autres comptes (j'ai vérifié dans les logs et /ipnames whois l'assure) :smiley:, ce n'est pas le mod qui l'en empêche !
Je ne perds donc pas espoir ! Il construit actuellement un immense château bien assez loin du spawn pour que ça ne soit pas grave s'il ressemble à ses maisons.

Je pense avoir la solution pour le paradoxe de names_per_ip : Lorsque Uraza a essayé de se connecter, l'IP de paul était toujours celle d'Uraza dans la base de donnée. Lorsque tu as vérifié avec la commande /ipnames whois, paul s'était déjà reconnecté, donc son IP n'était plus celle d'Uraza.

**Comment by mgl512** [comment]
J'ai banni MARIOXD par la commande normale, /ban. Pour harcèlement insupportable sur SkyHal et gaspillage de mon temps. Sa maison est protégée mais il lui pourrissait sa boite aux lettres, il entrait par usebug et devant moi. Et il a ce passif...

Je pense que c'est un gamin qui piquait une crise et je l'aurais banni temporairement, quelques jours, si xban2 avait été disponible. 

Ses ip ont l'air très différentes entre elles.

**Comment by paly2** [comment]
Ok. Ce joueur avait été en effet largement prévenu, et il a toujours continué. Jamais rien de grave, mais beaucoup...
