### ISSUE TITLE
Conflit de recette Entity Detector / Adjustable Player Detector

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#11]
Rapporté par SkyHal. Les deux objets viennent de MoreMesecons.

**Comment by paly2** [comment]
Effectivement,  je ne m'en étais jamais aperçu. J'avais sans-doute copié-collé des parties de code (les deux objets sont très proches) et oublié de modifier le craft. Je m'en occupe demain dès que je rentre.
Merci du signalement!

**Comment by paly2** [comment]
https://github.com/minetest-mods/MoreMesecons/commit/9ffc4147aa7c132cf13c99061544deb04fa740d6

J'ai aussi fait un submodule (volontaire pour une fois!) pour MoreMesecons https://github.com/paly2/Mynetest-server/commit/a6c1d3b101f7c73bb16389d23e8ce840c1afa0a4
