### ISSUE TITLE
Serveur public ou non ?

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#12]
Le serveur est encore une fois absent de la liste des serveurs publics.

**Comment by paly2** [comment]
Après des vacances de 8 jours, me revoilà :p

Oui effectivement c'est un problème embêtant, il faudra que j'arrête le serveur et que je modifie le minetest.conf sans qu'il soit lancé avant de le relancer afin de m'assurer que la modification sera bien prise en compte (plutôt qu'avec la commande /set pendant que le serveur tourne comme je le faisais, à laquelle je ne fais maintenant que moyennement confiance).

**Comment by mgl512** [comment]
Encore privé
