### ISSUE TITLE
names_per_ip

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#13]
C'est censé ne permettre que 2 comptes par ip mais "jonn" a 3 autres pseudos associés (par la commande /ipnames whois).

**Comment by paly2** [comment]
Bizarre, je vois ça dès demain.

**Comment by paly2** [comment]
Je spoupçonne fortement une ancienne version du protocole (notamment, inférieure à la verison 22), qui n'entraînerait pas d'appel à minetest.register_on_prejoinplayer (seulement à minetest.register_on_joinplayer). À vérifier. Impossible de communiquer avec ce joueur pour connaître la version de son client.

**Comment by mgl512** [comment]
Il est Français, il a une maison commune avec 4 autres joueurs en face du centre commercial mais il ne me répond plus en jeu depuis quelques jours. Il connecte souvent plusieurs de ses pseudos en même temps.

**Comment by paly2** [comment]
Il semblerait en fait que Yolo soit un usurpateur. Il a visiblement un client hyper-modifié (ce qui explique qu'il n'y a pas d'appel à minetest.register_on_prejoinplayer, il n'envoie pas la commande du protocole correspondante ; de plus, il semble qu'il soit intuable, même avec la commande /kill ou /hp).

**Comment by mgl512** [comment]
Le client est obligé de se conformer à un protocole de communication sinon il ne pourrait pas jouer du tout. Bien sûr ça doit être possible d'en utiliser un vieux buggé ou incomplet à dessein.

Pour la mort, c'est le serveur qui gère les points de vie. S'il décide qu'il est mort, il lui envoie un event "on die", vide son inventaire, enclenche son respawn au point de spawn et probablement d'autres trucs. Je ne sais pas à quel point on peut tricher avec ça. Si le client ne répond pas du tout au "on die", je pense qu'il ne peut plus intéragir avec le serveur ou les autres joueurs. Du côté des joueurs normaux, j'imagine qu'on ne le voit plus bouger, qu'il est mort à côté de ses ossements. De son côté à lui, j'imagine que c'est comme quand on est déco et qu'on ne le sait pas. Tout ce qu'il peut faire n'est que local. 

C'est peut-être pour ça qu'il ne répond à rien, il teste un client modifié. Si ça pose vraiment un problème, il faudrait le faire nous-mêmes pour voir ce qu'il se passe exactement côté serveur et côté joueur. Ou poser la question aux devs. Avoir une idée des évènements exacts qui sont envoyés au client quand il perd des points de vie et quand il meurt serait un bon début. Si c'est assez évident à repérer dans le code, je me compilerai un client qui refuse la mort. Je me rappelle que c'était assez facile de repérer comment gruger le refus de la minimap par le serveur quand ça buggait sur MFF.

**Comment by paly2** [comment]
Yolo est le seul à s'être connecté uniquement avec l'IP "usurpante". Mais la base de données de xban2 en bannirait trop si je ne la nettoie pas avant de ban.

**Comment by mgl512** [comment]
yolo, messi, jonn et jojo sont le même joueur pour moi. Il s'est connecté hier soir avec ces 4 comptes en même temps et faisait du PvP contre lui-même. J'ai appelé ça "PvSelf" dans le chat. Je me rappelle que messi a dit qu'il a perdu son stuff quand il jouait sous le nom de jojo, volé par un autre après du PvP. Je lui ai demandé pourquoi il n'avait pas pu récupérer rapidement son cube d'ossements et il n'a plus jamais répondu après ça.

**Comment by paly2** [comment]
Pourtant messi a aussi les IP 178.241.30.194 et 90.107.154.79... (L'IP usurpatrice est 88.181.239.144)

**Comment by paly2** [comment]
Je suis en train de nettoyer la base de données. Il y aura un reboot pour appliquer les modifications.

**Comment by mgl512** [comment]
> J'avais déjà fait un client qui ignore la mort, il suffit de commenter le contenu d'une fonction (send_damage ou quelque chose comme ça je crois). 

Moi je ne vois rien dans le code C qui permette d'être intuable. Le serveur informe le client de ses points de vie. Il ne peut pas les refuser. Tout ce que je vois à refuser de traiter, c'est une formspec "Ecran de mort". 

Le seul sendDamage() que j'ai trouvé vient de dégâts issus du client lui-même. Les dégâts de l'environnement du joueur sur lui-même. Le client regarde si on marche sur un bloc qui fait des dégâts et il les envoie au serveur si c'est le cas. Il corrige la respiration si on est dans un liquide. Il calcule des dégâts de chute si on tombe. Les dégâts de lave aussi. On peut apparemment se préserver de ces dégâts (et il y a un free_move qui a l'air intéressant aussi) mais surement pas de ceux des ABM (comme la radioactivité d'un subgame ou les cactus MFF) ou d'une commande comme /hp machin 0. Le sendDamage() semble même être protégé des dégâts négatifs qu'on pourrait essayer de s'infliger pour se rendre des points de vie. C'est un petit nombre positif utilisé uniquement dans une soustraction du côté du serveur. 

Les events on_prejoin et autres doivent être dans les scripts LUA parce que je ne les vois pas dans le code. les scripts LUA sont probablement une faille plus plausible que le code source d'ailleurs.

**Comment by paly2** [comment]
Vu en jeu, il est possible de "mourir" sans que le message de mort apparaisse (probablement ce qu'a fait Yolo).
Les on_prejoinplayer et on_joinplayer (seul le premier permettant de refuser la connexion d'un joueur) sont appelés dans le fichier network/serverpackethandler.cpp ([ici](https://github.com/minetest/minetest/blob/master/src/network/serverpackethandler.cpp#L197) et [là](https://github.com/minetest/minetest/blob/master/src/network/serverpackethandler.cpp#L487)). Il doit y avoir un moyen (en mélangeant les protocoles <= version 22 et > version 22 sans-doute) d'envoyer au serveur des commandes permettant d'initialiser la connexion sans faire appel aux on_prejoinplayer, ou bien en leur faisant appel de manière à ce qu'ils retournent toujours false.

**Comment by mgl512** [comment]
yolo a usurpé un nouveau joueur par rapport à mon compte précédent (d'après /ipnames whois) : steve, un joueur polonais qui parle mal anglais et qui demande très souvent du stuff. 

Pour le truc du on_prejoin qui ne marche pas avec son client, il a dû être banni de partout pour chercher à gruger ça... Est-ce que c'est sûr que c'est pas xban2 qui laisse encore passer quelqu'un de banni à cause de la précédence d'une ligne qui indique que le pseudo ou l'ip est ok dans sa base ?

**Comment by paly2** [comment]
Oui j'étais au courant pour steve.

La base de données de xban2 est propre. L'IP bannie ne s'y trouve qu'à un seul endroit, et elle est bannie.

Note: Des messages de logs sont apparus (générés par le on_prejoinplayer de xban2) indiquant que yolo a essayé de se connecter sans succès.

Je ferme cette issue. Il faudra la rouvrir si ce joueur réapparait en jeu.
