### ISSUE TITLE
Texte flottant (137, 38, -3)

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#14]
Le texte "Des graines" flotte sans panneau. C'est l'ancienne tour de Crystalhola / maison de disco. Je n'arrive pas à le supprimer avec worldedit. Ça ne marche pas non plus de mettre un bloc sur l'emplacement. 

Remettre un panneau au meme emplacement ?
J'ai peut-etre worldedité le bloc de derrière au lieu du bon aussi.

**Comment by paly2** [comment]
Ah oui, c'est un bug quand on supprime un panneau avec WE. L'entité (le texte) n'est pas supprimée. Le seul moyen de l'enlever (en plus, bien sûr, de la solution radicale /clearobjects) est de remettre un panneau puis de l'enlever "normalement".

**Comment by paly2** [comment]
Le texte a disparu tout seul, visiblement...
