### ISSUE TITLE
maptools:slab_stonebrick est invisible pour MTSatellite

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#16]
J'ai remplacé une partie des chemins publics par les nouvelles dalles incassables, qui apparaissent transparentes sur la carte du monde. On dirait du grief !

Il faut surement rajouter une entrée dans le fichier dont j'ai oublié le nom et l'emplacement, 'colors.txt' ou quelque chose comme ça.

**Comment by paly2** [comment]
Oui il faut faire un boot du serveur avec le mod automappercolors activé dans le world.mt. Ce mod génère automatiquement le colors.txt (ce qui serait assez lourd à faire à tous les démarrages, le script analyse tous les pixels de la texture supérieure de tous les nodes, raison pour laquelle ce mod n'est activé qu'occasionnellement). Je l'active tout de suite dans le world.mt (sans faire de commit) en prévision du prochain reboot (ou crash...), je le redésactiverai quand ce reboot aura eu lieu. Les chemins publics apparaitront alors correctement, ainsi que les shared chests et autres nouveaux nodes!
