### ISSUE TITLE
Ajouter des Stairs et Slabs incassables

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [paly2/Mynetest-server#19]
stairs:stair_cobble_u
stairs:slab_cobble_u

stairs:stair_stone_u
stairs:slab_stone_u

stairs:stair_stonebrick_u
stairs:slab_stonebrick_u

**Comment by AcidNinjaFWHR** [comment]
A corriger en remettant ce code dans le mod misc, afin de conserver maptools en sous-module.

**Comment by AcidNinjaFWHR** [comment]
NB: attention aux slabs incassables, car si l'on pose un autre slab dessus, cela se transforme en bloc cassable, il faut donc trouver un moyen d'empecher cela.

**Comment by paly2** [comment]
https://github.com/paly2/Mynetest-server/commit/8bd7d2ccbcda02f00a77214445e67efd39eb3309

Cela apporte les corrections suivantes:
* Ajoute les blocs à maptools, et non à stairs
* Ajoute les blocs depuis le mod misc, et non depuis maptools
* Permet de ne pas faire de bloc à partir de deux slabs posés l'un sur l'autre

**Comment by AcidNinjaFWHR** [comment]
ahhhhhh mince je ne suis pas assez efficace, car j'avais commencé à déplacer ça dans misc et mettre maptools en module, par contre j'avais pas trouvé pour que les 2 slabs ne se transforment pas.

Merci :+1:

**Comment by mgl512** [comment]
Les maptools:slab_stonebrick des routes n'ont pas de son. 
Pas vérifié s'il manque une dépendance aux fonctions de son de default ou juste la ligne de son dans la définition. Pas vérifié les autres blocs maptools ajoutés dans misc

**Comment by AcidNinjaFWHR** [comment]
corrigé dans 14664f35843145c2bf5a798e30d869ffab4243f7
il manquait effectivement les sons. je les ai mis en paramètre comme ça on pourra ajouter des slabs et stairs en bois incassable sans retoucher a la fonction.

**Comment by paly2** [comment]
OK, merci! Le paramètre est en effet la solution la plus propre :-)

**Comment by mgl512** [comment]
Les gens peuvent tourner les slabs au tournevis. les escaliers aussi surement

**Comment by paly2** [comment]
Nous n'avons que deux solutions pour empêcher les joueurs de tourner les blocs incassables (sans modifier le mod screwdriver).
* Faire une area sur les routes. Ce qui supprime l'intérêt d'avoir fait des slabs et stairs unbreakable.
* Supprimer l'attribut `paramtype2 = "facedir"` des stairs et slabs, ce qui impose leur orientation (ça n'est pas grave pour les slabs qui sont en pratique toujours posés à plat, mais ça l'est pour les stairs qui ne peuvent pas toujours être orientés vers le nord...).
