### ISSUE TITLE
Amnistie générale ?

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#20]
Des joueurs comme alexspectre38, banni à vie pour "Menace de mort et de piratage" ou UltraNexo au client cheaté ne sont plus bannis !

**Comment by paly2** [comment]
En effet. Plus aucun joueur n'est banni. Ni temporairement, ni défitivement. C'est incompréhensible! Aucune hypotèse ne permettrait de l'expliquer: comment un bug pourrait-il procéder aussi précisément à un tri ? Il faudrait un script fait à la main ! J'ai rebanni alexspectre38 et UltraNexo.

Notre xban.db actuel contient _moins d'entrées_ (note: les entrées comprennent aussi les joueurs qui ne sont pas bannis, seuls les joueurs whitelistés n'en ont pas) que celui du backup du 17 août.

**Comment by mgl512** [comment]
alexspectre38 a été banni le 17 septembre et a échoué à se reconnecter sous plusieurs autres  pseudos ensuite le même jour. Donc le fichier xban.db a été effacé entre le 17 et le 23 septembre.

**Comment by paly2** [comment]
J'ai du mal à imaginer 735 joueurs différents se connecter en une semaine...

**Comment by mgl512** [comment]
Regarde ce qu'il se passe dans les logs avec Prince50 par exemple: il est banni le 14 septembre, échoue à se reconnecter jusqu'au 21, le jour où le ban est levé automatiquement. Ou mieux: uranium. Il est banni pour 3 ans quand le debug.txt commence. Il échoue plusieurs fois à se connecter entre le 15 et le 20 et réussit le 22 à 22h30  (alors qu'il peut jouer depuis toujours avec son autre pseudo, nuclier).

**Comment by paly2** [comment]
Donc, ça a eu lieu le 21. Mais ça ne nous dit pas ce qui s'est précisément passé.

**Comment by mgl512** [comment]
Ni pourquoi la liste blanche est effacée aussi...

```
2016-09-19 17:31:44: ACTION[Server]: [xban] Upsilon bans fire until jeu. 22 sept. 2016 17:31:44 CEST for reason: Landscape grief
2016-09-19 17:31:44: ACTION[Server]: [xban] Banned Names/IPs: 
2016-09-19 17:31:53: ACTION[Server]: [xban] Upsilon unbans fire
2016-09-19 17:31:53: ACTION[Server]: [xban] Unbanned Names/IPs: 
2016-09-21 23:40:55: ACTION[Server]: [xban] Le_Docteur bans 30001 until ven. 23 sept. 2016 23:40:55 CEST for reason: Refus acharné de replanter le champ / Not replanting
2016-09-21 23:40:55: ACTION[Server]: [xban] Banned Names/IPs: 
2016-09-22 05:50:48: WARNING[Main]: [xban] Unable to load database: Deserialization failed
2016-09-22 16:44:41: ACTION[Server]: [xban] AcidDragon bans GamerBoy until the end of time for reason: insulte,menace,vole les autres joueurs...
2016-09-22 16:44:41: ACTION[Server]: [xban] Banned Names/IPs: 
2016-09-23 19:10:46: ACTION[Server]: [xban] Le_Docteur bans Admin until the end of time for reason: Name !
2016-09-23 19:10:46: ACTION[Server]: [xban] Banned Names/IPs:
```
C'est pas inquiétant la ligne `[xban] Unable to load database: Deserialization failed` ?

**Comment by paly2** [comment]
Remarquable. Je n'avais pas encore fouillé les logs à cet endroit. Ça dit tout: la désérialisation du fichier xban.db a échoué, xban2 c'est donc retrouvé avec une base de données vide, qu'il a enregistré en écrasant le vrai fichier au moment ou le serveur s'est arrêté.

**Comment by mgl512** [comment]
Oui, c'est merveilleux. J'apprécie particulièrement le simple warning et l'effacement total de la base. Ça devrait s'appeler xban_osef ou xban_yolo. 

C'est encore une situation où je trouve difficile à croire que les gros serveurs ne l'aient pas remarqué, comme les move_area() qui ne fonctionnaient qu'après redémarrage.

**Comment by AcidNinjaFWHR** [comment]
Je propose un patch simple
à chaque suppression ou ajout dans xban, on fait une backup de la base. ça peut etre fait en lua directement dans le mod. Au moins si y'a un souci on pourra revenir rapidement en arriere.

**Comment by paly2** [comment]
Remplacer la sauvegarde régulière par une sauvegarde à chaque changement est une bonne idée, mais plutôt que de faire un backup de la base, il faudrait simplement qu'xban2 se désactive entièrement lui-même (il suffit de faire une vérification dans les callbacks, sur un booléen appelé `active` par exemple, ainsi que et surtout sur la fonction `save_db`) en envoyant un mail (après avoir vérifié, bien sûr, l'existence du mod mail sur le serveur) aux modérateurs.

**Comment by AcidNinjaFWHR** [comment]
hummm pas compris en quoi envoyer un mail sauverai le fichier.

**Comment by paly2** [comment]
Cela ne sauve pas le fichier (c'est la désactivation de la fonction `save_db` qui le fait), mais cela signale qu'xban2 est inactif et que le fichier doit d'urgence être réparé (car une sérialisation qui échoue est causée par un fichier invalide).

**Comment by mgl512** [comment]
Regardez ce que j'ai trouvé sur xban_yolo dans les logs: 
```
2016-09-25 12:16:00: ACTION[Server]: [xban] Le_Docteur bans simpura08 until dim. 02 oct. 2016 12:16:00 CEST for reason: Chat abuse
2016-09-25 12:16:00: ACTION[Server]: [xban] Banned Names/IPs: 
2016-09-25 13:06:51: WARNING[Main]: [xban] Unable to load database: Deserialization failed
2016-09-25 14:03:11: WARNING[Main]: [xban] Unable to load database: Deserialization failed
```
Merci à GamerBoy, banni à vie, que j'ai vu connecté sur la map.

**Comment by paly2** [comment]
_EDIT: La 2ème ligne "Deserialization failed", c'est parce que la base est vraiment vide, purgée grâce au redémarrage échoué précédemment..._

Étrange, en fait. La version écrasée du fichier devrait être valide.

**Comment by mgl512** [comment]
Il n'y a eu aucun ajout à la base de données entre les deux lignes d'erreur. Je ne suis pas sur que xban sauve sa base si elle n'a pas été modifiée, je n'ai rien lu de son code.

**Comment by AcidNinjaFWHR** [comment]
Salut,
si si xban sauve automatiquement la base toutes les 5 minutes, qu'il y ait changement ou non.
mais cela n'explique pas le bug.

**Comment by paly2** [comment]
Je suis certain (à 100%) que la base de données actuelle d'xban2 est valide, j'ai vu minetest la désérialiser sous mes yeux.

Tout semble refonctionner. Depuis le dernier reboot, le ban d'uranium (par exemple) n'a pas été perdu.
Cependant la cause du bug n'est toujours pas connue.

**Comment by paly2** [comment]
Je ferme car xban2 refonctionne bien. N'hésitez pas à réouvrir.
