### ISSUE TITLE
Too much lag !

### ISSUE THREAD

**Issue by paly2** [paly2/Mynetest-server#4]
This server has a huge lag (sometimes, more than a minute). I have to reduce it.

How ? If Pipeworks would be removed, I think the lag would be greatly reduced. But Pipeworks is very useful.

The lag is also caused by a very little Internet speed, but this is more difficult to fix (less datas to transfer... Is this really possible ?).

So, I ask every players: what do you think I can do to reduce lag ? Are you ready to remove Pipeworks ?

**Comment by mgl512** [comment]
Yes. Try to remove Pipeworks for a few days at least, to test the lag. 
Remove drop_leaves too then.

**Comment by paly2** [comment]
Ok I will remove Pipeworks from this afternoon to friday, to test if there is less lag. I think drop_leaves may be also useful to get big trees leaves - I think I won't remove it.

**Comment by paly2** [comment]
Actually, Pipeworks is not loaded: the lag is gone. I think it will be removed definitely, but the test continues.

**Comment by mgl512** [comment]
Note: the oil essence became an unknown object.

**Comment by paly2** [comment]
Do you know if there is a way to create an alias for every `pipeworks:*` item which converts it to `default:nyancat_rainbow` (without writing a `minetest.register_alias` for every of the many, many pipeworks items) ? I tryed with a regex, it didn't work.

**Comment by mgl512** [comment]
I don't know any other way.

**Comment by paly2** [comment]
Pipeworks is now removed (aliases has been created).
