### ISSUE TITLE
Conflit de recettes sur cobweb

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#5]
**mobs:cobweb** et **xdecor:cobweb** ont la même recette (des fils en 5 de dé à jouer). J'imagine alias ou nouvelle recette pour l'un d'eux. Je ne vois pas comment faire ça en dehors de ces mods eux-mêmes, comment le faire sans causer de maintenance dans les mises à jour. Changer une recette modifierait moins de fichiers q'un alias.

**Comment by paly2** [comment]
Merci d'avoir remarqué ce problème,

Supprimer un des deux items de la table `minetest.registered_items` pour le rempacer par un alias pourrait-il fonctionner ?
Par exemple, dans le mod `misc` (auquel les dépendances `mobs` et `xdecor` seraient rajoutées):
``` lua
minetest.registered_items["xdecor:cobweb"] = nil
minetest.register_alias("xdecor:cobweb", "mobs:cobweb")
```
Je testerai cela une fois le DNB passé, samedi. Si ça fonctionne, je ferai la modification ainsi, sinon, je préfère tout de même faire un alias plutôt que de changer une recette.

**Comment by mgl512** [comment]
> Supprimer un des deux items de la table minetest.registered_items pour le rempacer par un alias pourrait-il fonctionner ?

Non. J'ai déjà testé ce genre de truc (avec registered_nodes), le moteur refuse de faire l'alias meme si l'objet est nil.

**Comment by mgl512** [comment]
Ce code/hack ne marche pas trop bien :
```
if minetest.get_modpath("mobs") ~= nil
   and minetest.get_modpath("xdecor") ~= nil
   then
	-- use the cobweb from mobs
	--minetest.registered_nodes["xdecor:cobweb"] = nil
	minetest.registered_items["xdecor:cobweb"] = nil
	minetest.register_alias("xdecor:cobweb", "mobs:cobweb")
end
```
Dans mes tests, j'ai mis ça à l'intérieur d'un modpack "compatibilité d'objets" dont cobweb est un mod dont le depends.txt contient "mobs?" et "xdecor?"

La recette de xdecor:cobweb est supprimée mais l'objet xdecor:cobweb reste présent sous ce nom dans le monde. Il y en a 2 au dessus de la cheminée de ma ferme du spawn dans le vrai monde Mynetest. Si on inverse et que c'est la cobweb de xdecor qu'on garde, la canne à pêche en mithril devient incraftable parce qu'elle demande toujours mobs:cobweb comme ingrédient et c'est incraftable. Ça ne change rien qu'on mette l'entrée "registered_nodes[]" à nil ou pas. 

En fait l'alias passe dans les logs mais ne fait rien du tout, on a le même résultat en le commentant. C'est la ligne `minetest.registered_items["xdecor:cobweb"] = nil`
qui supprime la recette. Ça n'est pas du tout un alias, c'est un **Ugly hack**.

**Comment by mgl512** [comment]
Je rouvre parce qu'il y a une nouvelle fonction ajoutée cette semaine dans l'API LUA qui pourrait permettre de résoudre ce conflit de recette sans toucher au mod xdecor:  **minetest.clear_craft()**
(https://github.com/minetest/minetest/commit/281e9f39fdffd106e79122ae23e2b5443a5daea3)

**Comment by paly2** [comment]
Magnifique ! Je recompile le serveur !

**Comment by paly2** [comment]
Nouvelle fonction de l'API: `minetest.unregister_item` et `minetest.register_alias_force`. Actuellement disponibles sur le serveur.

Elles devraient permettre de corriger ce genre de problèmes à l'avenir
