### ISSUE TITLE
Je suis ban de l'IRC

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#6]
Le_Docteur ?!?

**Comment by paly2** [comment]
Je suis aussi ban !!

**Comment by mgl512** [comment]
Et Mehdi35 a bien un mot de passe. Je ne sais pas comment son compte a été usurpé

**Comment by mgl512** [comment]
Uraza n'était pas ban, elle était sur IRC mais pas là quand moi j'étais banni. Je ne sais pas pour disco. Je suppose que tu as unban tout le monde de toute manière.

**Comment by paly2** [comment]
Le joueur ArcaDeGo a la même IP que Mehdi35 (ils habitent donc très certainement au même endroit, ce qui expliquerait que ArcaDeGo connaisse le mot de passe de Mehdi35).
Je n'ai donc rien changé dans les ipban.txt (je ne souhaite bannir que ArcaDeGo, pas Mehdi35).

**Comment by mgl512** [comment]
OK. Je suis sûr que ce sont deux joueurs différents et je ne voudrais pas non plus bannir le vrai Mehdi35 qui n'a rien fait. ArcaDeGo n'a peur de rien : sous le nom de Mehdi35, il s'est construit une maison juste à côté de chez jg avec les cubes très discrets d'obsidian brick qu'il lui a volé dans ses coffres en cheatant. Tout ça a été rollback.
