### ISSUE TITLE
Usurpations de comptes

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#7]
Mehdi35 puis johan. johan dit qu'il a pas de frère et ça se passait la nuit. Il a grief sa maison.

Là j'ai banni WolfTueur parce qu'il parlait comme un débile. Je pense que c'était un faux aussi.

Je comprends pas comment il fait pour s'emparer des comptes. je suis perdu. J'ai tenté de me connecter sous le nom Mehdi35 avec les mots de passe "Mehdi35" et "123". Je me suis connecté sous le compte de thomas qui n'a pas de mot de passe.

Il faudrait regarder avec quelle IP WolfTueur s'est connecté récemment par rapport à son IP habituelle. Et johan. 

Mehdi35, johan, WolfTueur (banni), thomas

L'énigme est résolue pour johan et thomas : je me suis connecté avec leurs comptes sans mot de passe.
Pour WolfTueur, j'ai tenté. mais comme je l'ai ban, ça m'a juste dit "connection timed out".

J'ai créé le compte "usurpateur666" pour faire des trucs. Vérifier qu'on peut changer son mot de passe entre autres

**Comment by mgl512** [comment]
La liste des comptes usurpés s'est encore étendue mais ça reste des évènements passés Celle des comptes sans mot de passe aussi. L'usurpateur a volé les ressources de différents joueurs et les a accumulées sur son compte usurpé final on dirait. C'était une belle escroquerie. Un peu courte. J'espère qu'il a posté une vidéo de ses aventures d'usurpateur sur Mynetest. 

Quelques joueurs se demandent si l'usurpateur est un ancien joueur qui ne vient plus. Plusieurs pseudos circulent. Si tu a le temps de faire un grep de l'IP xbannie dans les logs, ça serait bien de retrouver ses pseudos de départ, non usurpés. Je crois que quelqu'un s'est fait défoncer sa maison non protégée juste parce qu'il est soupçonné.

**Comment by paly2** [comment]
Oula !
Liste des joueurs qui ne se sont connectés qu'avec l'IP de l'usurpateur:
* ArcaDeGo (vu précédemment)
* Mehdi35 (vu précédemment)
* bryan200 (ne s'est connecté qu'une seule fois d'ailleurs)
* kunna (ne pas confondre avec kumma, dont l'usurpateur a d'ailleurs essayé d'usurper le compte, en vain grâce au mot de passe)

Les logs ne remontent qu'au 22 mai (dernière date à laquelle je les ai nettoyés), impossible donc de savoir si un ancien joueur avait aussi cette IP.

La liste de comptes que l'usurpateur a usurpé/essayé d'usurper est en effet très longue, comme l'indiquent les logs.

Je ne sais pas de qui la maison a été détruite, ni par qui, ni où était cette maison, je n'ai pas du tout eu vent de cette histoire, je n'ai pas les informations pour la traiter...

**Comment by mgl512** [comment]
Mehdi35 a été un véritable joueur et son IP d'origine doit être perdue. Son compte a un mot de passe maintenant. A tous les coups il n'en avait pas au départ et c'est l'usurpateur qui lui en a mis un. Ce ne sont pas des frères ou des gens qui habitent au même endroit, ce sont les activités de l'usurpateur qui font croire qu'ils ont la même IP. Mehdi est un ami de disco, qui lui a donné du stuff (et à l'usurpateur aussi sous cette ID). Ça doit être possible de dire à disco de demander à Mehdi s'il avait un mot de passe ou d'essayer de se connecter. Sa véritable IP devrait passer parce qu'elle n'est pas bannie. En revanche, le mot de passe...

ArcaDeGo s'est connecté un jour, récemment, et a demandé du stuff et une maison je crois. Le lendemain il s'est connecté sous le compte de Mehdi35 et a annoncé qu'il était ArcaDeGo qui s'était emparé du compte de Mehdi. Il a pillé les coffres de jg par usebug et l'a refait plusieurs fois sous des ID usurpées. Mehdi35 et ArcaDeGo ont déjà joué ensemble sur Romstation d'après Akito. 

Je n'ai jamais vu les autres ni remarqué aucune trace d'eux. Ce sont surement ses pseudos de départ. L'usurpateur a dû commencer par se ballader et repérer des pseudos sur des coffres verrouillés et des areas pour trouver des comptes à usurper. 

La maison détruite, c'est celle de guigui31, collée à l'arène. Ça n'est pas très important, elle était vraiment moche et facile. Plusieurs joueurs l'ont cassée et ont volé des trucs comme des fours.

**Comment by paly2** [comment]
Merci de tes nouvelles informations !

J'ai relu les logs à propos de Mehdi35 pour m'apercevoir que l'usurpateur avait changé le mot de passe de Mehdi35, comme tu l'as dit, interdisant l'accès au vrai Mehdi35. Je l'ai réinitialisé. Je réouvre l'issue, visiblement tout n'est pas terminé.

Voici la liste de joueurs dont le compte s'est fait usurpé, et qui devront d'urgence mettre un mot de passe pour ceux qui ne l'ont pas déjà fait:
* Mehdi35
* WolfTueur
* paul
* Winner
* thomas
* johan

Voici la la liste de joueurs que l'usurpateur a essayé d'usurper, en vain grâce au mot de passe:
* ermir
* jg
* Dragons
* Uraza
* Le_Docteur
* Lord_discodlm57
* kumma
* AkitoNaaki93
* SB
* F

Quant à guigui31, il est certain qu'il n'a rien à voir dans cette histoire.

**Comment by mgl512** [comment]
Je pensais que stayfino s'était fait usurper aussi. Je l'ai trouvé sans stuff devant la maison de WolfTueur quand j'ai usurpé moi-même son compte. Il n'avait rien non plus dans ses coffres chez lui. J'ai fait un rollback de ses actions et un stock de fer est revenu dans ses coffres. johan dit que stayfino était différent la dernière fois qu'il l'a croisé, et qu'il demandait du stuff il me semble.  

Winner est le plus récent usurpé que j'ai découvert. Je l'ai trouvé sans stuff devant chez lui avec le Nyan de sa façade cassé et absent de son inventaire. J'ai fait un rollback.

**Comment by paly2** [comment]
Les trois dernières connexions de stayfino ont une IP complètement différente de celle de toutes les connexions précédents. Toutefois il ne s'agit pas de l'IP de l'usurpateur.

**Comment by mgl512** [comment]
> Les trois dernières connexions de stayfino ont une IP complètement différente de celle de toutes les connexions précédents. Toutefois il ne s'agit pas de l'IP de l'usurpateur.

L'une d'elles est la mienne. Ce sont peut-etre d'autres joueurs qui ont essayé son compte comme moi. Le stock important de fer qui réapparait dans son coffre après rollback suggère qu'il y a eu une usurpation malveillante quand même. Rien de mieux que ça n'est réapparu d'ailleurs. 

kunna et f n'ont pas de mot de passe et sont au point de spawn. Je n'ai pas vérifié s'ils ont interact. bryan200 a un mot de passe. Ça doit être le pseudo d'entrée de l'usurpateur sur le serveur. Je suppose que je pourrais réinitialiser le mot de passe du joueur, qu'il n'y a pas besoin qu'il soit connecté, sinon la fonction ne servirait pas à grand chose. Je pourrais en prendre le contrôle et voir ou il est et son stuff. Je suppose qu'il n'a rien, ce compte ne lui a servi qu'à observer les noms sur les coffres verrouillés et les areas.

**Comment by paly2** [comment]
> Je suppose que je pourrais réinitialiser le mot de passe du joueur, qu'il n'y a pas besoin qu'il soit connecté, sinon la fonction ne servirait pas à grand chose.

Oui bien sûr, les commandes /clearpassword et /setpassword peuvent s'exécuter même quand le joueur n'est pas connecté.

> Je pourrais en prendre le contrôle et voir ou il est et son stuff. Je suppose qu'il n'a rien, ce compte ne lui a servi qu'à observer les noms sur les coffres verrouillés et les areas.

Oui c'est une bonne idée de vérifier, mais en effet il serait peu probable qu'il y ait quelque chose. Si tu souhaites le faire n'hésite pas.

**Comment by paly2** [comment]
J'ai à nouveau un problème.
L'IP 91.86.249.35 a été ban avec xban2 le 25 juin à 12h23. Le même jour à 15h38, cette IP - sans aucun changement ! - se connecte sous le nom de paul et change son mot de passe. En fait, il semblerait que contrairement à ce qui est écrit sur le [sujet du forum](https://forum.minetest.net/viewtopic.php?t=9315), la commande /xban ne fonctionne qu'avec un nom, pas avec une IP.

J'ai fait une [issue sur le dépôt de xban2](https://github.com/minetest-mods/xban2/issues/8).

**Comment by mgl512** [comment]
Yeah !   Si ça se trouve, /xban_record montre cette IP comme bannie avec plein de détails parce qu'elle l'est dans ses tables alors qu'elle ne l'est pas en réalité. Il y a même une interface graphique pour du vent. 

Mais comment personne n'a pu s'en rendre compte avant ?  Ils n'ont aucun problème avec des joueurs les gros serveurs ?  Ils ne sont pas modérés ?

**Comment by paly2** [comment]
xban2 fonctionne, je l'ai testé avec ma propre IP !
Je me demande si l'usurpateur n'aurait pas trouvé le moyen de rendre son client insensible au ban. Je ne connais pas assez bien le fonctionnement interne de l'engine pour savoir si c'est possible.

**Comment by mgl512** [comment]
xban aurait du mettre un message dans les logs sur la tentative de connexion de paul avec l'IP bannie s'il avait fonctionné. Y est-il ? Il faut peut-etre redémarrer le serveur pour que ce mod mette sa liste de joueurs bannis à jour, je ne sais pas. Ou il ne sauvegarde pas sa base de données dès qu'on ajoute une entrée bannie et l'usurpateur a profité d'un moment où xban2 a

**Comment by paly2** [comment]
Non, xban2 ne met aucun message dans les logs lors des tentatives de connexion de joueurs bannnis. Et non il ne faut pas redémarrer mon serveur, puisque ça a fonctoinné avec ma propre IP, et j'ai essayé de me co quelques secondes après m'être ban...

**Comment by mgl512** [comment]
Donc il transmet sa base de données sur les bannis au serveur (mais sans passer par le fichier 'ipban.txt' d'après la doc) et c'est lui qui s'occupe de rejeter ou accepter la connexion. Je vois pas comment on peut cracker son client pour gruger le serveur là-dessus: le serveur a sa liste d'IP et de joueurs bannis, il a pas besoin de demander son IP au client, il l'a par les protocoles de communications réseau (en plus le client aurait apparemment transmis la vraie). A moins que le serveur lui demande s'il veut bien être banni, le client ne peut rien faire.

Il faut chercher une faille de ce genre dans src/client.cpp: :smile:
```
/* This code is executed when the server tells you you are banned
 * Reply 0 to agree to your fate
 * or something else to play anyway with no trace in the logs
 */
void ban_ack()
{
	send_to_server(0); // <--- CRACK ME HERE
}
```
Je préfère penser qu'xban2 ne marche pas quand on l'installe. Un peu comme quand on veut importer ses bookmarks dans un nouveau navigateur...

**Comment by mgl512** [comment]
Nous avons eu visite d'un stayfino sur le serveur, 88.162.3.71. Le joueur qui a été usurpé plusieurs fois mais pas par l'Usurpateur Officiel. Il s'est reconnecté ensuite sous le pseudo wolftueur tout en minuscules. J'ai banni cette IP avec xban "Usurpation de comptes" et **j'ai été banni aussi** parce que je fais partie des IP qui ont usurpé le compte stayfino au moment de l'afaire de l'usurpateur. J'ai laissé mon compte dans cet état au cas où tu voudrais regarder la base de données xban2. 

J'ai usurpé Winner, miniloup et probablement d'autres encore. Pourvu qu'ils ne soient jamais bannis :sob:

**Comment by paly2** [comment]
Normalement, maintenant c'est bon...
La base de donnée devrait à présent être propre et tu ne devrais plus être ban. J'implémente la whitelist dont j'ai parlé sur IRC. Je ferme l'issue, j'espère que je n'aurai pas à la rouvrir... :confused:

**Comment by mgl512** [comment]
D'après thomas et johan, le stayfino qui a pris le compte wolftueur est le vrai. johan le connait personnellement et thomas l'a eu au téléphone. Ils disent qu'il s'est appelé wolftueur parce qu'il n'arrivait pas à mettre un mot de passe à stayfino et qu'il rageait. Mais pourquoi usurper en minuscules un compte déjà existant ?  Si tu veux faire des recherches dans tes logs (sur l'ip par exemple) pour voir s'il faut le débannir, fais-le. Moi ça ne me dérange pas qu'il reste banni.

**Comment by paly2** [comment]
Je l'ai unban ce matin, c'était bien le vrai stayfino qui a pris le compte wolftueur.

**Comment by mgl512** [comment]
> c'était bien le vrai stayfino qui a pris le compte wolftueur

Quelle idée lumineuse de sa part, prendre le compte en minuscules sous lequel le véritable usurpateur a été banni !  Il faut faire attention à ce que le vrai usurpateur n'ait pas été unban dans la chaine d'actions de xban . A cause de ça:

> wolftueur [= stayfino] a quitté le jeu dès qu'il s'est connecté. Il a écrit un truc dans le chat [...] et il a été déco. J'ai juste eu le temps de regarder son ip C'est peut-être xban qui l'a pisté et kické. J'ai banni son ip alors qu'il n'était plus en jeu mais il était peut-être déjà autobanni à ce moment-là.

Il faudra prévenir johan et thomas. stayfino n'arrive pas a mettre de mot de passe, il faudra peut-etre lui en mettre un. Mais comment être sur que c'est le bon qui se connecte, espérer que son ip n'a pas changé ?

**Comment by paly2** [comment]
> Il faut faire attention à ce que le vrai usurpateur n'ait pas été unban dans la chaine d'actions de xban.

Non, mais l'IP de stayfino est présente deux fois dans la base de données de xban2... La première fois, associée uniquement avec le pseudo de stayfino (c'est ce qui était ban), et la deuxième fois, avec "worldtueur" (tout en minuscules avec un d), "wolftueur" (tout en minuscules), "Johan" (avec une majuscule), "thomas", "thomastrop", "kellian", "Crystalhola", "88.175.25.218", "77.193.238.188".

> Mais comment être sur que c'est le bon qui se connecte, espérer que son ip n'a pas changé ?

Lorsque les IP dynamiques changent, on retrouve au minimum le premier (généralement les 2 voire les 3 premiers) nombre de l'IPv4 identique. Lorsque les 4 nombres sont différents il est très probable que la personne en question ne se trouve plus au même endroit (c'est-à-dire que ça ne soit pas elle...).

**Comment by paly2** [comment]
Note: Il semblerait que la whitelist de xban2 ne fonctionne pas: lorsque xban2 est activé, la connexion time out systématiquement. J'ai dû désactiver xban2. Bizarre, ça ne le faisait pas pendant mes tests. Je suis en train de chercher la cause (on dirait une boucle infinie, mais elle serait trahie par une augmentation de l'utilisation du CPU, ce qui n'est pas le cas...)

**Comment by mgl512** [comment]
J'ai un doute sur Coco542016, connecté le 17 juillet, qui est censé etre un ami de disco. Il s'est connecté sous le nom d'exodusFaceDanus le 15 juillet. Des joueurs rapportent des messages obscènes sous l'identité d'un joueur qui n'y est en fait pour rien dans le chat en sa présence. J'ai entendu parler de ce usebug de chat mais je ne le connais pas moi-même. Coco avait exploré loin a l'ouest quand c'était le vrai il y a longtemps. La il annonce qu'il est nouveau mais il a exploré loin au sud quand meme. donc c'est peut-etre le vrai. Suspicion...
