### ISSUE TITLE
La flèche en or ne tient pas compte du status PvP

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#8]
Elle inflige des dégâts quel que soit le status du tireur et de la cible. Bizarrement, celle en acier touche sans faire de dégât si la cible désactive son PvP d'après nos tests sur le serveur.

EDIT:
J'imagine que c'est l'auteur (ou le destinataire, je n'y comprends rien) qui ne va pas dans le code des dégâts des flèches. Il y a une variable self.player définié quelque part alors on peut essayer de l'utiliser dans ce Necronomikode, copié-collé et répliqué dans plusieurs fichiers de flèches:

```
diff --git a/mods/throwing/golden_arrow.lua b/mods/throwing/golden_arrow.lua
index ead0c20..fc8427e 100644
--- a/mods/throwing/golden_arrow.lua
+++ b/mods/throwing/golden_arrow.lua
@@ -43,14 +43,18 @@ THROWING_arrow_gold_ENTITY.on_step = function(self, dtime)
 	self.timer = self.timer + dtime
 	local pos = self.object:getpos()
 	local node = minetest.get_node(pos)
+	local hitter = self.object
 
 	if self.timer > 0.2 then
+		if self.player ~= nil then
+			hitter = self.player
+		end
 		local objs = minetest.get_objects_inside_radius({x = pos.x, y = pos.y, z = pos.z}, 1)
 		for k, obj in pairs(objs) do
 			if obj:get_luaentity() ~= nil then
 				if obj:get_luaentity().name ~= "throwing:arrow_gold_entity" and obj:get_luaentity().name ~= "__builtin:item" then
 					local damage = 5
-					obj:punch(self.object, 1.0, {
+					obj:punch(hitter, 1.0, {
 						full_punch_interval = 1.0,
 						damage_groups= {fleshy = damage},
 					}, nil)
@@ -59,7 +63,7 @@ THROWING_arrow_gold_ENTITY.on_step = function(self, dtime)
 				end
 			else
 				local damage = 5
-				obj:punch(self.object, 1.0, {
+				obj:punch(hitter, 1.0, {

```
Je ne vois pas comment tester ça en singleplayer.

**Comment by paly2** [comment]
Effectivement il est très galère de tester un code multiplayer (il faut faire tourner plusieurs instances de Minetest sur le même PC, en priant pour que la mémoire de celui-ci ne sature pas).

La variable player correspond en effet à l'envoyeur, c'est une très bonne idée d'essayer de l'utiliser, cela fonctionnera sans doute. Je vais appliquer la modification sans tester, je ne vois dans le code aucune raison qu'il cause un crash.

Ce qui est bizarre, c'est que la flèche d'acier ne fonctionne pas sur les joueurs qui n'ont pas le PvP activé. Je vais aussi appliquer la modification sur la flèche d'acier.
