### ISSUE TITLE
Le serveur a rebooté en créatif ?!?

### ISSUE THREAD

**Issue by mgl512** [paly2/Mynetest-server#9]
Il est marqué en créatif sur servers.minetest.net

Je l'ai crash hier soir avec une commande rollback_check() mal paramétrée.

**Comment by paly2** [comment]
Effectivement il avait bel et bien rebooté en créatif. Grave erreur de ma part, dont je ne m'étais même pas aperçu, heureusement que tu as ouvert cette issue !

Cela est survenu car j'avais lancé le client minetest sur la machine serveur, ce qui a eu pour conséquence de modifier le minetest.conf.
